In [151]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [152]:
import pandas as pd
import numpy as np
file_path = r"/content/drive/MyDrive/Proyecto AyP/Calories.csv"
data = pd.read_csv(file_path)
data

,id,Sex,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,0,male,36,189.0,82.0,26.0,101.0,41.0,150.0
1,1,female,64,163.0,60.0,8.0,85.0,39.7,34.0
2,2,female,51,161.0,64.0,7.0,84.0,39.8,29.0
3,3,male,20,192.0,90.0,25.0,105.0,40.7,140.0
4,4,female,38,166.0,61.0,25.0,102.0,40.6,146.0
...,...,...,...,...,...,...,...,...,...
749995,749995,male,28,193.0,97.0,30.0,114.0,40.9,230.0
749996,749996,female,64,165.0,63.0,18.0,92.0,40.5,96.0
749997,749997,male,60,162.0,67.0,29.0,113.0,40.9,221.0
749998,749998,male,45,182.0,91.0,17.0,102.0,40.3,109.0
749999,749999,female,39,171.0,65.0,19.0,97.0,40.6,103.0

In [153]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          750000 non-null  int64
 1   Sex         750000 non-null  object
 2   Age         750000 non-null  int64
 3   Height      750000 non-null  float64
 4   Weight      750000 non-null  float64
 5   Duration    750000 non-null  float64
 6   Heart_Rate  750000 non-null  float64
 7   Body_Temp   750000 non-null  float64
 8   Calories    750000 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 51.5+ MB

In [154]:
data.describe()

,id,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
count,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000
mean,374999.500000,41.420404,174.697685,75.145668,15.421015,95.483995,40.036253,88.282781
std,216506.495284,15.175049,12.824496,13.982704,8.354095,9.449845,0.779875,62.395349
min,0.000000,20.000000,126.000000,36.000000,1.000000,67.000000,37.100000,1.000000
25%,187499.750000,28.000000,164.000000,63.000000,8.000000,88.000000,39.600000,34.000000
50%,374999.500000,40.000000,174.000000,74.000000,15.000000,95.000000,40.300000,77.000000
75%,562499.250000,52.000000,185.000000,87.000000,23.000000,103.000000,40.700000,136.000000
max,749999.000000,79.000000,222.000000,132.000000,30.000000,128.000000,41.500000,314.000000

In [155]:
print(data.isna().sum())

id            0
Sex           0
Age           0
Height        0
Weight        0
Duration      0
Heart_Rate    0
Body_Temp     0
Calories      0
dtype: int64

In [156]:
print(data.duplicated().sum())

0

Al no tener datos duplicados ni datos nulos, se procede a buscar  columna por columna datos atipicos. Para ello se usa una tecnica de dispersión estadistica IQR que establece un intervalo y las muestras que esten por fuera se eliminan.

**Columna "Sex"**

In [157]:
print(f"Los géneros son",data["Sex"].unique())#No tiene datos atipicos

Los géneros son ['male' 'female']

**Columna "Age"**

In [193]:
print(f"El maximo de edad {data["Age"].max()} años \nEl minimo de edad es {data["Age"].min()} años") #Se conoce el rango de edad

El maximo de edad 79 años
El minimo de edad es 20 años

In [191]:
Q1=data['Age'].quantile(0.25)
Q3=data['Age'].quantile(0.75)
IQR=Q3-Q1
lim_inferior=Q1-1.5*IQR
lim_superior=Q3+1.5*IQR
data=data[(data['Age']>=lim_inferior) & (data['Age']<=lim_superior)]
data.info() #No se eliminaron datos

<class 'pandas.core.frame.DataFrame'>
Index: 734886 entries, 0 to 749999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          734886 non-null  int64
 1   Sex         734886 non-null  object
 2   Age         734886 non-null  int64
 3   Height      734886 non-null  float64
 4   Weight      734886 non-null  float64
 5   Duration    734886 non-null  float64
 6   Heart_Rate  734886 non-null  float64
 7   Body_Temp   734886 non-null  float64
 8   Calories    734886 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 56.1+ MB

**Columna "Height"**

In [160]:
print(f"El máximo de altura es {data["Height"].max()}")

El máximo de altura es 222.0

In [161]:
print(data[data['Height']>210.0])

            id   Sex  Age  Height  Weight  Duration  Heart_Rate  Body_Temp  \
2987      2987  male   65   213.0   113.0      18.0       103.0       40.9
5599      5599  male   76   211.0   113.0      29.0       107.0       41.3
7839      7839  male   54   211.0   111.0       3.0        81.0       38.4
10362    10362  male   41   213.0   110.0      29.0       116.0       40.9
12249    12249  male   42   212.0   112.0      15.0        84.0       40.2
...        ...   ...  ...     ...     ...       ...         ...        ...
738418  738418  male   52   212.0   111.0      20.0       102.0       40.7
738632  738632  male   35   211.0   111.0       2.0        78.0       38.2
739818  739818  male   50   212.0   111.0      20.0       102.0       40.7
740717  740717  male   76   211.0   110.0      25.0       110.0       40.8
747258  747258  male   52   212.0   111.0      20.0        99.0       40.6

        Calories
2987       142.0
5599       261.0
7839        12.0
10362      228.0
12249       61.0
...          ...
738418     142.0
738632       5.0
739818     142.0
740717     240.0
747258     130.0

[330 rows x 9 columns]

In [163]:
print("la altura minima es ", data['Height'].min())

la altura minima es  126.0

In [177]:
Q1=data['Height'].quantile(0.25)
Q3=data['Height'].quantile(0.75)
IQR=Q3-Q1
lim_inferior=Q1-1.5*IQR
lim_superior=Q3+1.5*IQR
data=data[(data['Height']>=lim_inferior) & (data['Height']<=lim_superior)]#Elimina 14 datos atipicos (alturas muy bajas o muy altas)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 749986 entries, 0 to 749999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          749986 non-null  int64
 1   Sex         749986 non-null  object
 2   Age         749986 non-null  int64
 3   Height      749986 non-null  float64
 4   Weight      749986 non-null  float64
 5   Duration    749986 non-null  float64
 6   Heart_Rate  749986 non-null  float64
 7   Body_Temp   749986 non-null  float64
 8   Calories    749986 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 57.2+ MB


**Columna "Weight"**

In [167]:
print(f"El peso maximo es {data['Weight'].max()} \nEl peso minimo es {data['Weight'].min()} ")

El peso maximo es 132.0
El peso minimo es 36.0

In [179]:
#Al no tener un rango dado buscamos con IQR datos atipicos
Q1=data['Weight'].quantile(0.25)
Q3=data['Weight'].quantile(0.75)
IQR=Q3-Q1
lim_inferior=Q1-1.5*IQR
lim_superior=Q3+1.5*IQR
data=data[(data['Weight']>=lim_inferior) & (data['Weight']<=lim_superior)]#Elimino 4 datos atipicos
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 749982 entries, 0 to 749999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          749982 non-null  int64
 1   Sex         749982 non-null  object
 2   Age         749982 non-null  int64
 3   Height      749982 non-null  float64
 4   Weight      749982 non-null  float64
 5   Duration    749982 non-null  float64
 6   Heart_Rate  749982 non-null  float64
 7   Body_Temp   749982 non-null  float64
 8   Calories    749982 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 57.2+ MB

**Columna "Duration"**

In [169]:
print(f"La duración minima es {data["Duration"].min()} y la duración máxima {data['Duration'].max()}")

La duración minima es 1.0 y la duración máxima 30.0

In [180]:
Q1=data['Duration'].quantile(0.25)
Q3=data['Duration'].quantile(0.75)
IQR=Q3-Q1
lim_inferior=Q1-1.5*IQR
lim_superior=Q3+1.5*IQR
data=data[(data['Duration']>=lim_inferior) & (data['Duration']<=lim_superior)]
data.info()#No hay datos atipicos en esta columna

<class 'pandas.core.frame.DataFrame'>
Index: 749982 entries, 0 to 749999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          749982 non-null  int64
 1   Sex         749982 non-null  object
 2   Age         749982 non-null  int64
 3   Height      749982 non-null  float64
 4   Weight      749982 non-null  float64
 5   Duration    749982 non-null  float64
 6   Heart_Rate  749982 non-null  float64
 7   Body_Temp   749982 non-null  float64
 8   Calories    749982 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 57.2+ MB

**Columna "Heart_Rate"**

In [181]:
print(f"El ritmo cardiaco maximo {data['Heart_Rate'].max()} y el minimo {data['Heart_Rate'].min()}")

El ritmo cardiaco maximo 128.0 y el minimo 67.0

In [182]:
data[(data['Heart_Rate'] < 75) & (data['Age'] < 30)] #En personas jovenes una frecuencia cardiaca menor a 75 estando en actividad fisica es inusual

,id,Sex,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
490,490,female,22,152.0,50.0,2.0,74.0,38.4,5.0
710,710,female,24,166.0,61.0,2.0,74.0,38.2,3.0
800,800,female,20,161.0,58.0,2.0,74.0,38.3,6.0
1546,1546,female,22,161.0,67.0,1.0,72.0,37.7,3.0
1767,1767,female,29,171.0,63.0,1.0,70.0,37.9,1.0
...,...,...,...,...,...,...,...,...,...
747012,747012,female,21,182.0,71.0,3.0,74.0,38.8,6.0
747376,747376,female,27,159.0,68.0,1.0,71.0,37.4,2.0
747859,747859,male,28,165.0,66.0,1.0,70.0,38.0,2.0
748811,748811,male,28,184.0,88.0,1.0,74.0,37.7,1.0
749332,749332,female,25,162.0,59.0,1.0,73.0,38.1,2.0

In [183]:
Q1=data['Heart_Rate'].quantile(0.25)
Q3=data['Heart_Rate'].quantile(0.75)
IQR=Q3-Q1
lim_inferior=Q1-1.5*IQR
lim_superior=Q3+1.5*IQR
data=data[(data['Heart_Rate']>=lim_inferior) & (data['Heart_Rate']<=lim_superior)]
data.info() #Elimina 36 datos atipicos

<class 'pandas.core.frame.DataFrame'>
Index: 749946 entries, 0 to 749999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          749946 non-null  int64
 1   Sex         749946 non-null  object
 2   Age         749946 non-null  int64
 3   Height      749946 non-null  float64
 4   Weight      749946 non-null  float64
 5   Duration    749946 non-null  float64
 6   Heart_Rate  749946 non-null  float64
 7   Body_Temp   749946 non-null  float64
 8   Calories    749946 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 57.2+ MB

**Columna "Body_temp"**

In [185]:
print(f"La temperatura corporal maxima es {data['Body_Temp'].max()} y la minima {data['Body_Temp'].min()}") #Una temperatura corporal en mayor a 40,5 es inusual

La temperatura corporal maxima es 41.5 y la minima 38.0

In [184]:
Q1_temp = data['Body_Temp'].quantile(0.25)
Q3_temp = data['Body_Temp'].quantile(0.75)
IQR_temp = Q3_temp - Q1_temp

limite_inferior_temp = Q1_temp - (1.5 * IQR_temp)
limite_superior_temp = Q3_temp + (1.5 * IQR_temp)

data=data[(data['Body_Temp'] >= limite_inferior_temp) & \
                   (data['Body_Temp'] <= limite_superior_temp)]
data.info() #Elimina 14919 datos

<class 'pandas.core.frame.DataFrame'>
Index: 735027 entries, 0 to 749999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          735027 non-null  int64
 1   Sex         735027 non-null  object
 2   Age         735027 non-null  int64
 3   Height      735027 non-null  float64
 4   Weight      735027 non-null  float64
 5   Duration    735027 non-null  float64
 6   Heart_Rate  735027 non-null  float64
 7   Body_Temp   735027 non-null  float64
 8   Calories    735027 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 56.1+ MB

**Columna "Calories"**

In [189]:
print("minimo de calorias quemadas es de ", data['Calories'].min(), "y el maximo es de ", data['Calories'].max())

minimo de calorias quemadas es de  1.0 y el maximo es de  314.0

In [190]:
Q1=data['Calories'].quantile(0.25)
Q3=data['Calories'].quantile(0.75)
IQR=Q3-Q1
lim_inferior=Q1-1.5*IQR
lim_superior=Q3+1.5*IQR
data=data[(data['Calories']>=lim_inferior) & (data['Calories']<=lim_superior)]
data.info() #Se eliminaron 141 datos

<class 'pandas.core.frame.DataFrame'>
Index: 734886 entries, 0 to 749999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          734886 non-null  int64
 1   Sex         734886 non-null  object
 2   Age         734886 non-null  int64
 3   Height      734886 non-null  float64
 4   Weight      734886 non-null  float64
 5   Duration    734886 non-null  float64
 6   Heart_Rate  734886 non-null  float64
 7   Body_Temp   734886 non-null  float64
 8   Calories    734886 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 56.1+ MB

Finalmente, se eliminaron 15114 datos del data set